name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: tty-pt/ci/.github/workflows/all-in-one.yml@main
    with:
      name: libndc
      deps: "libqmap,libxylem,libssl-dev"
      deps_apk: "libqmap,libxylem,openssl-dev"
      deps_pacman: "libqmap,libxylem,openssl"
      deps_pacman_mingw: "mingw-w64-libqmap,mingw-w64-libxylem,mingw-w64-openssl"
      deps_rpm: "libqmap,libxylem,openssl-devel"
      deps_brew: "libqmap,libxylem,openssl"
      deps_openbsd: "libqmap,libxylem,openssl"
      deps_winget: "mingw-w64-x86_64-openssl"
      deps_winget_tty: "libqsys,libqmap,libxylem"
      publish_to: "deb,apk,rpm,brew,openbsd,winget"
    secrets:
      HOST: ${{ secrets.OPENBSD_HOST }}
      USER: ${{ secrets.OPENBSD_USER }}
      SSH_KEY: ${{ secrets.OPENBSD_SSH_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.OPENBSD_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.OPENBSD_GPG_PASSPHRASE }}
      GPG_KEYID: ${{ secrets.OPENBSD_GPG_KEY_ID }}
      ABUILD_PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
      ABUILD_PUBLIC_KEY: ${{ secrets.ABUILD_PUBLIC_KEY }}
      TAP_TOKEN: ${{ secrets.TAP_TOKEN }}
